variables:
  SDK_URL: "https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip" 
  ANDROID_HOME: "$CI_PROJECT_DIR/package/android-sdk" 
  ANDROID_VERSION: 26 
  ANDROID_BUILD_TOOLS_VERSION: 26.0.2


stages:
 - build
 - package
 - test
 - publish

build:
  stage: build
  # image: 'mobile/android-linux-build:stable'
  tags:
   - darwin
  only:
  - master
  - tags
  before_script:
  - ./project/prepare_env.sh
  script:
  - ./project/build_package.sh
  artifacts:
    paths:
    - com.unity.mobile.notifications/Runtime/Android/Plugins/Android
  after_script:
  - /opt/post_build_script.sh    

package:
  stage: package
  tags:
  - darwin
  only:
  - master
  - tags
  before_script:
  - ./com.unity.mobile.notifications/prepare_upm-ci.sh
  script:
  - cd com.unity.mobile.notifications
  - ./package_package.sh
  artifacts:
    paths:
    - com.unity.mobile.notifications/upm-ci~/packages/*

test:
  stage: test
  tags:
  - darwin
  only:
  - master
  - tags
  before_script:
  - ./com.unity.mobile.notifications/prepare_upm-ci.sh
  script:
  - cd com.unity.mobile.notifications
  - ./test_package.sh
  artifacts:
    paths:
    - com.unity.mobile.notifications/upm-ci~/packages/*

publish:
  stage: publish
  image: package-ci/win10:stable
  only:
  - master
  - tags
  tags:
  - bokken-job
  script:
    - upm-ci package publish
  